In [2]:
import pandas as pd
import numpy as np
import time

In [2]:
relationship = pd.read_csv('relationship_new.csv',encoding = 'utf-8')
relationship = relationship.drop('Unnamed: 0',axis = 1)
relationship

:START_ID       :TYPE  :END_ID
0            362633  birthPlace  5533231
1            362633  birthPlace  1056076
2            362633  deathPlace  5348598
3            362633  deathPlace  3773633
4           1324976  birthPlace  3429596
...             ...         ...      ...
13188787    4326933        type  1862626
13188788     193423        type  1862626
13188789    4635056        type  5175169
13188790     470273        type  1862626
13188791    5464191        type  1862626

[13188792 rows x 3 columns]

# Test Demo

In [3]:
test_array = [[1,0,1],[1,0,2],[1,1,2],[1,2,0]]

In [4]:
df = pd.DataFrame(test_array, columns = ['value', 'x', 'y'], dtype = float)
df

value    x    y
0    1.0  0.0  1.0
1    1.0  0.0  2.0
2    1.0  1.0  2.0
3    1.0  2.0  0.0

In [23]:
count = df['y'].value_counts()
# 2.0 in count.index
# count[0]
count

2.0    2
0.0    1
1.0    1
Name: y, dtype: int64

In [18]:
list0 = [(1,1),(1,2)]

In [21]:
list0[1][1]

2

In [5]:
# 计算S
N = 3
S = list()
for i in range(N):
    temp_value = 0
    for j in range(len(df)):
        if df.y[j]==i:
            temp_value += df.value[j]
    S.append(temp_value)
S

[1.0, 1.0, 2.0]

In [9]:
# 变为"转移概率df"
for i in range(len(S)):
    for j in range(len(df)):
        if df.y[j] == i:
            df.value[j] = 1/S[i]
df

value    x    y
0    1.0  0.0  1.0
1    0.5  0.0  2.0
2    0.5  1.0  2.0
3    1.0  2.0  0.0

In [12]:
# page rank function
def page_rank_df(df, threshold = 10e-3, beta = 0.8):
#     N = 4691099
    N = 3
    r_old = np.array([0 for i in range(N)])
    r_new = np.array([(1/N) for i in range(N)])
    while np.sum(np.abs(r_old - r_new)) > threshold:
        r_old = r_new
        dot_result = []
        for i in range(N): #x
            temp_result = 0
            if i in df.x:
                temp_df = df[df.x==i]
                for j in range(N): #y
                    if j in list(temp_df.y):
#                         print('r_new[j]:',r_new[j])
#                         print(temp_df[temp_df.x==i][temp_df.y==j].value.iloc[0])
                        number = temp_df[temp_df.x==i][temp_df.y==j].value.iloc[0]
                        temp_result+=number*r_new[j]
            dot_result.append(temp_result)
            print('dot_result:', dot_result)
        r_new = beta * np.array(dot_result)
        print(r_new)
        S = np.sum(r_new)
        r_new += (1-S)/N
    return r_new

In [13]:
page_rank_df(df)

dot_result: [0.5]
dot_result: [0.5, 0.16666666666666666]
dot_result: [0.5, 0.16666666666666666, 0.3333333333333333]
[0.4        0.13333333 0.26666667]
dot_result: [0.36666666666666664]
dot_result: [0.36666666666666664, 0.16666666666666666]
dot_result: [0.36666666666666664, 0.16666666666666666, 0.4666666666666667]
[0.29333333 0.13333333 0.37333333]
dot_result: [0.42]
dot_result: [0.42, 0.22]
dot_result: [0.42, 0.22, 0.36]
[0.336 0.176 0.288]
dot_result: [0.42]
dot_result: [0.42, 0.17733333333333332]
dot_result: [0.42, 0.17733333333333332, 0.4026666666666667]
[0.336      0.14186667 0.32213333]
dot_result: [0.40293333333333337]
dot_result: [0.40293333333333337, 0.19440000000000002]
dot_result: [0.40293333333333337, 0.19440000000000002, 0.4026666666666667]
[0.32234667 0.15552    0.32213333]
dot_result: [0.41658666666666666]
dot_result: [0.41658666666666666, 0.1944]
dot_result: [0.41658666666666666, 0.1944, 0.3890133333333333]
[0.33326933 0.15552    0.31121067]
dot_result: [0.41112533333333

array([0.39556693, 0.22131285, 0.38312021])

# A smallllllll test

In [14]:
relationship = relationship.drop(':TYPE',axis = 1)
relationship = relationship.rename(columns={':START_ID':'x',':END_ID':'y'})
ones = [1 for i in range(len(relationship))]
relationship['value']=ones
relationship = relationship[['value','x','y']]
relationship

value        x        y
0             1   362633  5533231
1             1   362633  1056076
2             1   362633  5348598
3             1   362633  3773633
4             1  1324976  3429596
...         ...      ...      ...
13188787      1  4326933  1862626
13188788      1   193423  1862626
13188789      1  4635056  5175169
13188790      1   470273  1862626
13188791      1  5464191  1862626

[13188792 rows x 3 columns]

In [ ]:
# test = relationship[:100].astype('float')
# N = 4691099
# S = list()
# start = time.time()

# for i in range(N):
#     temp_value = 0
#     for j in range(len(test)):
#         if test.y[j]==i:
#             temp_value += test.value[j]
#     S.append(temp_value)

# for i in range(len(S)):
#     for j in range(len(test)):
#         if test.y[j] == i:
#             test.value[j] = 1/S[i]

# page_rank_test(test)

# end = time.time()
# t = end-start
# print('t:',t)

In [ ]:
# # A failed page rank function
# def page_rank_df(df, threshold = 10e-3, beta = 0.8):
#     N = len(df)
#     r_old = np.array([0 for i in range(N)]).reshape((N, 1))
#     r_new = np.array([(1/N) for i in range(N)]).reshape((N, 1))
#     while np.sum(np.abs(r_old - r_new)) > threshold:
#         r_old = r_new
#         dot_result = []
#         for i in range(N): #x
#             temp_result = 0
#             temp_df = df[df.x==i]
#             if temp_df.empty:
#                 dot_result.append(0)
#                 continue
# #             print(len(temp_df))
# #             print(temp_df)
#             for j in range(N): #y
#                 for k in range(len(temp_df)):
#                     if temp_df.y[k]==j:
#                         temp_result+=temp_df.value[k]*r_new[j]
#             print(temp_result)
#             dot_result.append(temp_result)
#             print(dot_result)
# #         r_new = beta * np.dot(graph_mat, r_old)
#         r_new = beta * dot_result
#         S = np.sum(r_new)
#         r_new += (1-S)/N
#     return r_new